/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLayoutRouteImport } from './routes/app/_layout'
import { Route as AppStartIndexRouteImport } from './routes/app/start/index'
import { Route as AppLayoutIndexRouteImport } from './routes/app/_layout/index'
import { Route as AppLayoutSettingsIndexRouteImport } from './routes/app/_layout/settings/index'
import { Route as AppLayoutIncomesIndexRouteImport } from './routes/app/_layout/incomes/index'
import { Route as AppLayoutExpensesIndexRouteImport } from './routes/app/_layout/expenses/index'
import { Route as AppLayoutCategoriesIndexRouteImport } from './routes/app/_layout/categories/index'
import { Route as AppLayoutBudgetsIndexRouteImport } from './routes/app/_layout/budgets/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/app/_layout',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStartIndexRoute = AppStartIndexRouteImport.update({
  id: '/app/start/',
  path: '/app/start/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutSettingsIndexRoute = AppLayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutIncomesIndexRoute = AppLayoutIncomesIndexRouteImport.update({
  id: '/incomes/',
  path: '/incomes/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutExpensesIndexRoute = AppLayoutExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutCategoriesIndexRoute =
  AppLayoutCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutBudgetsIndexRoute = AppLayoutBudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppLayoutRouteWithChildren
  '/app/': typeof AppLayoutIndexRoute
  '/app/start/': typeof AppStartIndexRoute
  '/app/budgets/': typeof AppLayoutBudgetsIndexRoute
  '/app/categories/': typeof AppLayoutCategoriesIndexRoute
  '/app/expenses/': typeof AppLayoutExpensesIndexRoute
  '/app/incomes/': typeof AppLayoutIncomesIndexRoute
  '/app/settings/': typeof AppLayoutSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppLayoutIndexRoute
  '/app/start': typeof AppStartIndexRoute
  '/app/budgets': typeof AppLayoutBudgetsIndexRoute
  '/app/categories': typeof AppLayoutCategoriesIndexRoute
  '/app/expenses': typeof AppLayoutExpensesIndexRoute
  '/app/incomes': typeof AppLayoutIncomesIndexRoute
  '/app/settings': typeof AppLayoutSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/_layout': typeof AppLayoutRouteWithChildren
  '/app/_layout/': typeof AppLayoutIndexRoute
  '/app/start/': typeof AppStartIndexRoute
  '/app/_layout/budgets/': typeof AppLayoutBudgetsIndexRoute
  '/app/_layout/categories/': typeof AppLayoutCategoriesIndexRoute
  '/app/_layout/expenses/': typeof AppLayoutExpensesIndexRoute
  '/app/_layout/incomes/': typeof AppLayoutIncomesIndexRoute
  '/app/_layout/settings/': typeof AppLayoutSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/'
    | '/app/start/'
    | '/app/budgets/'
    | '/app/categories/'
    | '/app/expenses/'
    | '/app/incomes/'
    | '/app/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/start'
    | '/app/budgets'
    | '/app/categories'
    | '/app/expenses'
    | '/app/incomes'
    | '/app/settings'
  id:
    | '__root__'
    | '/'
    | '/app/_layout'
    | '/app/_layout/'
    | '/app/start/'
    | '/app/_layout/budgets/'
    | '/app/_layout/categories/'
    | '/app/_layout/expenses/'
    | '/app/_layout/incomes/'
    | '/app/_layout/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AppStartIndexRoute: typeof AppStartIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout': {
      id: '/app/_layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/start/': {
      id: '/app/start/'
      path: '/app/start'
      fullPath: '/app/start/'
      preLoaderRoute: typeof AppStartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout/': {
      id: '/app/_layout/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/settings/': {
      id: '/app/_layout/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppLayoutSettingsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/incomes/': {
      id: '/app/_layout/incomes/'
      path: '/incomes'
      fullPath: '/app/incomes/'
      preLoaderRoute: typeof AppLayoutIncomesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/expenses/': {
      id: '/app/_layout/expenses/'
      path: '/expenses'
      fullPath: '/app/expenses/'
      preLoaderRoute: typeof AppLayoutExpensesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/categories/': {
      id: '/app/_layout/categories/'
      path: '/categories'
      fullPath: '/app/categories/'
      preLoaderRoute: typeof AppLayoutCategoriesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/budgets/': {
      id: '/app/_layout/budgets/'
      path: '/budgets'
      fullPath: '/app/budgets/'
      preLoaderRoute: typeof AppLayoutBudgetsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
  AppLayoutBudgetsIndexRoute: typeof AppLayoutBudgetsIndexRoute
  AppLayoutCategoriesIndexRoute: typeof AppLayoutCategoriesIndexRoute
  AppLayoutExpensesIndexRoute: typeof AppLayoutExpensesIndexRoute
  AppLayoutIncomesIndexRoute: typeof AppLayoutIncomesIndexRoute
  AppLayoutSettingsIndexRoute: typeof AppLayoutSettingsIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutIndexRoute: AppLayoutIndexRoute,
  AppLayoutBudgetsIndexRoute: AppLayoutBudgetsIndexRoute,
  AppLayoutCategoriesIndexRoute: AppLayoutCategoriesIndexRoute,
  AppLayoutExpensesIndexRoute: AppLayoutExpensesIndexRoute,
  AppLayoutIncomesIndexRoute: AppLayoutIncomesIndexRoute,
  AppLayoutSettingsIndexRoute: AppLayoutSettingsIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AppStartIndexRoute: AppStartIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
